project:
  type: website
  output-dir: docs

website:
  title: "Lab0Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - dv.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

